export const INIT_SESSION = 'INIT_SESSION';
export const ANALYZE_PDF = 'ANALYZE_PDF';
export const RENDER_PREVIEW = 'RENDER_PREVIEW';
export const START_COMPRESSION = 'START_COMPRESSION';
export const CANCEL = 'CANCEL';

// Event Types for Success
export const ANALYSIS_COMPLETE = 'ANALYSIS_COMPLETE';
export const PREVIEW_READY = 'PREVIEW_READY';
export const COMPRESSION_COMPLETE = 'COMPRESSION_COMPLETE';
export const PROGRESS_UPDATE = 'PROGRESS_UPDATE';
export const SESSION_INITIALIZED = 'SESSION_INITIALIZED';
